services:
  label_studio:
    image: heartexlabs/label-studio:latest
    container_name: label_studio
    ports:
      - "8508:8080"
    volumes:
      - ${HOME}/labelstudio-data:/label-studio/data
    restart: unless-stopped
    
  neo4j:
    image: neo4j:community
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "${NEO4J_USER}/${NEO4J_PASSWORD}"
    volumes:
      - ${HOME}/neo4j-data:/data
      - ${HOME}/neo4j-logs:/logs
    restart: unless-stopped

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ${HOME}/redis-data:/data
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD}"
    restart: unless-stopped